def get_banks():
    return {
        "0100": "Komerční banka, a.s.",
        "0300": "Československá obchodní banka, a. s.",
        "0600": "MONETA Money Bank, a.s.",
        "0710": "Česká národní banka",
        "0800": "Česká spořitelna, a.s.",
        "2010": "Fio banka, a.s.",
        "2020": "MUFG Bank (Europe) N.V. Prague Branch",
        "2060": "Citfin, spořitelní družstvo",
        "2070": "TRINITY BANK a.s.",
        "2100": "Hypoteční banka, a.s.",
        "2200": "Peněžní dům, spořitelní družstvo",
        "2220": "Artesa, spořitelní družstvo",
        "2250": "Banka CREDITAS a.s.",
        "2260": "NEY spořitelní družstvo",
        "2275": "Podnikatelská družstevní záložna",
        "2600": "Citibank Europe plc, organizační složka",
        "2700": "UniCredit Bank Czech Republic and Slovakia, a.s.",
        "3030": "Air Bank a. s.",
        "3040": "Western Union International Bank GmbH, organizační složka",
        "3050": "BNP Paribas Personal Finance SA, odštěpný závod",
        "3060": "PKO BP S.A., Czech Branch",
        "3500": "ING Bank N.V.",
        "4000": "Max banka a.s.",
        "4141": "FCM BANK Praha, odštěpný závod",
        "4300": "Národní rozvojová banka, a.s.",
        "5051": "AS Inbank, odštěpný závod",
        "5500": "Raiffeisenbank a.s.",
        "5800": "J&T BANKA, a.s.",
        "6000": "PPF banka a.s.",
        "6100": "Raiffeisenbank a.s. (do 31. 12. 2021 Equa bank a.s.)",
        "6200": "COMMERZBANK Aktiengesellschaft, pobočka Praha",
        "6210": "mBank S.A., organizační složka",
        "6300": "BNP Paribas S.A., pobočka Česká republika",
        "6700": "Všeobecná úverová banka a.s., pobočka Praha",
        "7910": "Deutsche Bank Aktiengesellschaft Filiale Prag, organizační složka",
        "7950": "Raiffeisen stavební spořitelna a.s.",
        "7960": "ČSOB Stavební spořitelna, a.s.",
        "7970": "MONETA Stavební Spořitelna, a.s.",
        "7990": "Modrá pyramida stavební spořitelna, a.s.",
        "8030": "Volksbank Raiffeisenbank Nordoberpfalz eG pobočka Cheb",
        "8040": "Oberbank AG pobočka Česká republika",
        "8060": "Stavební spořitelna České spořitelny, a.s.",
        "8090": "Česká exportní banka, a.s.",
        "8150": "HSBC Continental Europe, Czech Republic",
        "8190": "Sparkasse Oberlausitz-Niederschlesien",
        "8198": "FAS finance company s.r.o.",
        "8199": "MoneyPolo Europe s.r.o.",
        "8211": "Saxo Bank A/S, organizační složka",
        "8231": "Bank Gutmann Aktiengesellschaft, pobočka Česká republika",
        "8241": "SMBC Bank EU AG Prague Branch",
        "8250": "Bank of China (CEE) Ltd. Prague Branch",
        "8265": "Industrial and Commercial Bank of China Limited, Prague Branch, odštěpný závod",
        "8500": "Ferratum Bank plc",
    }
